package com.spring.application.models;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.spring.application.models.enumeration.Tax;
import lombok.extern.slf4j.Slf4j;

import java.io.Serializable;

@Slf4j
@DynamoDBTable(tableName = "businessProfile")
public class BusinessProfile implements Serializable {

    private static final long serialVersionUID = -3534650012619938612L;
    private String id;

    private String companyName;
    private String legalName;
    private Address businessAddress;
    private Address legalAddress;
    private Tax tax;
    private String email;
    private String website;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @DynamoDBAttribute(attributeName = "companyName")
    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) { this.companyName = companyName; }


    @DynamoDBAttribute(attributeName = "legalName")
    public String getLegalName() {
        return legalName;
    }

    public void setLegalName(String legalName) { this.legalName = legalName; }


    @DynamoDBAttribute(attributeName = "businessAddress")
    public Address getBusinessAddress() {
        return businessAddress;
    }

    public void setBusinessAddress(Address businessAddress) { this.businessAddress = businessAddress; }


    @DynamoDBAttribute(attributeName = "legalAddress")
    public Address getLegalAddress() {
        return legalAddress;
    }

    public void setLegalAddress(Address legalAddress) { this.legalAddress = legalAddress; }


    @DynamoDBAttribute(attributeName = "tax")
    public Tax getTax() {
        return tax;
    }

    public void setTax(Tax tax) { this.tax = tax; }

    @DynamoDBAttribute(attributeName = "email")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) { this.email = email; }

    @DynamoDBAttribute(attributeName = "website")
    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) { this.website = website; }



}