package com.spring.application.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.spring.application.models.enumeration.Product;
import lombok.extern.slf4j.Slf4j;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Slf4j
@DynamoDBTable(tableName = "productSubscription")
public class ProductSubscription implements Serializable {

    private static final long serialVersionUID = -3534650012619938612L;
    private String id;

    private UserProfile user;
    private BusinessProfile businessProfile;
    private List<Product> products;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return id;
    }

    public void setUserId(String id) {
        this.id = id;
    }


    @DynamoDBAttribute(attributeName = "user")
    public UserProfile getUserProfile() {
        return user;
    }

    public void setUserProfile(UserProfile user) { this.user = user; }


    @DynamoDBAttribute(attributeName = "businessProfile")
    public BusinessProfile getBusinessProfile() {
        return businessProfile;
    }

    public void setBusinessProfile(BusinessProfile businessProfile) { this.businessProfile = businessProfile; }


    @DynamoDBAttribute(attributeName = "products")
    public List<Product> getProducts() {
        return products;
    }

    public void setProducts(List<Product> products) {
        this.products = products;
    }




}
