package com.spring.application.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.spring.application.models.enumeration.Product;
import com.spring.application.utils.EnumMarshallConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@Slf4j
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "productSubscription")
public class ProductSubscription implements Serializable {

    private static final long serialVersionUID = -3534650012619938612L;
    private String id;

    private String userId;
    private BusinessProfile businessProfile;
    private List<Product> products;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @DynamoDBRangeKey(attributeName = "userId")
    public String getUserProfileId() {
        return userId;
    }

    public void setUserProfile(String user) { this.userId = user; }

    @DynamoDBAttribute(attributeName = "businessProfile")
    public BusinessProfile getBusinessProfile() {
        return businessProfile;
    }

    public void setBusinessProfile(BusinessProfile businessProfile) { this.businessProfile = businessProfile; }

//    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBTypeConverted(converter = EnumMarshallConverter.class)
    public List<Product> getProducts() {
        return products;
    }

    public void setProducts(List<Product> products) {
        this.products = products;
    }




}
